routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Post;
use App\Setting;
use App\Rating;
use App\View;
use App\User;

Auth::routes();

Route::get('/', function() {

	$filter['flag'] = 1; 

    $posts = Post::where($filter);
    if(isset(\Auth::user()->type) && \Auth::user()->type != 'admin') {
        $posts->where('bulletin', 'like', '%'.\Auth::user()->type.'%');
    }

	$posts = $posts->get();

	foreach ($posts as $key => $post) {
		if(isset($post->files[0]->filename)) {
			$posts[$key]['filename'] = $post->files[0]->filename;
		} else {
			$posts[$key]['filename'] = '';
		}

		$ratings = Rating::where('post_id', $post->id)->get();

		$aveRating = 0;

		if(!$ratings->isEmpty()) {
			$rate = [
				5 => 0,
				4 => 0,
				3 => 0,
				2 => 0,
				1 => 0
				];
			foreach ($ratings as $value) {
				$rate[$value['rating']]++; 
			}


			$totalWeight = 0;
			$totalReviews = 0;

			foreach ($rate as $weight => $numberofReviews) {
			    $WeightMultipliedByNumber = $weight * $numberofReviews;
			    $totalWeight += $WeightMultipliedByNumber;
			    $totalReviews += $numberofReviews;
			}

			//divide the total weight by total number of reviews
			$aveRating = $totalWeight / $totalReviews;

			$aveRating = floor($aveRating);
		}

		$posts[$key]['aveRating'] = $aveRating;

		 $authId = null;
        if(isset(Auth::user()->id)) {
            $authId = Auth::user()->id;
        } 

        $posts[$key]['authId'] = $authId;

        $limit = 250;

         $string = strip_tags($post['desc']);

        if (strlen($string) > $limit) {
            // truncate string
            $stringCut = substr($string, 0, $limit);

            // make sure it ends in a word so assassinate doesn't become ass...
            $string = substr($stringCut, 0, strrpos($stringCut, ' ')).'... <a href="/post/'.$post['id'].'">Read More</a>';
        }

        $posts[$key]['desc'] = $string;

	}

    $bg = Setting::where('type', 'bg')->first();
    $font = Setting::where('type', 'font')->first();


    return view('index', ['posts' => $posts, 'bg' => $bg, 'font' => $font]);
});

Route::get('/home', 'PostsController@index');
Route::get('/post/{id}', function($id) {
	$post = Post::where('id', $id)->first();

	$view = new View();
	$view->post_id = $id;

	$view->save();

	$ratings = Rating::where('post_id', $id)->get();

	$aveRating = 0;

	if(!$ratings->isEmpty()) {
		$rate = [
			5 => 0,
			4 => 0,
			3 => 0,
			2 => 0,
			1 => 0
			];
		foreach ($ratings as $key => $value) {
			$rate[$value['rating']]++; 
		}


		$totalWeight = 0;
		$totalReviews = 0;

		foreach ($rate as $weight => $numberofReviews) {
		    $WeightMultipliedByNumber = $weight * $numberofReviews;
		    $totalWeight += $WeightMultipliedByNumber;
		    $totalReviews += $numberofReviews;
		}

		//divide the total weight by total number of reviews
		$aveRating = $totalWeight / $totalReviews;

		$aveRating = floor($aveRating);
	}

    $template = Setting::where('type', 'template')->first();

  $bg = Setting::where('type', 'bg')->first();
    $font = Setting::where('type', 'font')->first();


    return view('post-detail', ['post' => $post, 'aveRating' => $aveRating, 'template' => $template, 'bg' => $bg, 'font' => $font]);
});

Route::get('/admin', 'AdminController@index');
Route::resource('/admin/users','AdminUsersController');
Route::resource('/admin/posts', 'PostsController');
Route::get('/admin/view', 'PostsController@view');
Route::get('/admin/rating', 'PostsController@rating');
Route::get('/admin/bulletin', 'PostsController@bulletin');

Route::get('/admin/users', [
	'uses' => 'AdminUsersController@index',
	'as' => 'admin',
	'middleware' => 'roles',
	'roles' => ['admin']
]);	

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/api/posts', 'ApiPostsController@index');
Route::post('/api/rating/create', 'ApiPostsController@rating');
Route::get('/api/views', 'ApiPostsController@views');
Route::get('/admin/settings', 'SettingController@index');
Route::get('/admin/settings/bg', 'SettingController@bg');
Route::resource('/admin/settings', 'SettingController');
Route::get('/api/settings', 'ApiPostsController@template');
Route::get('user/{id}/delete', ['as' => 'users.delete', 'uses' => 'AdminUsersController@destroy']);

Route::get('/api/posts/preview', 'ApiPostsController@preview');

Route::get('/ajax/users', 'AdminUsersController@indexApi');
Route::get('/preview', function() {

	if(isset($_GET['type'])) {

		if($_GET['type'] == 'general') {
            $posts = Post::orderBy('id', 'DESC')->get();

		}  else {
            $posts = Post::where('bulletin', 'like', '%'.$_GET['type'].'%')
            ->orderBy('id', 'DESC')->get();
			
		}
   } else if(isset($_GET['q']) && !empty($_GET['q'])) { 
        $posts = new Post();

        $posts = $posts->where('author', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('title', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('type', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('bulletin', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('desc', 'LIKE', "%" . $_GET['q'] . "%")->get();
    }


	// foreach ($posts as $key => $post) {
	// 	if(isset($post->files[0]->filename)) {
	// 		$posts[$key]['filename'] = $post->files[0]->filename;
	// 	} else {
	// 		$posts[$key]['filename'] = '';
	// 	}

	// 	$ratings = Rating::where('post_id', $post->id)->get();

	// 	$aveRating = 0;

	// 	if(!$ratings->isEmpty()) {
	// 		$rate = [
	// 			5 => 0,
	// 			4 => 0,
	// 			3 => 0,
	// 			2 => 0,
	// 			1 => 0
	// 			];
	// 		foreach ($ratings as $key => $value) {
	// 			$rate[$value['rating']]++; 
	// 		}


	// 		$totalWeight = 0;
	// 		$totalReviews = 0;

	// 		foreach ($rate as $weight => $numberofReviews) {
	// 		    $WeightMultipliedByNumber = $weight * $numberofReviews;
	// 		    $totalWeight += $WeightMultipliedByNumber;
	// 		    $totalReviews += $numberofReviews;
	// 		}

	// 		//divide the total weight by total number of reviews
	// 		$aveRating = $totalWeight / $totalReviews;
	// 	}

	// 	$posts[$key]['aveRating'] = $aveRating;

	// 	 $authId = null;
 //        if(isset(Auth::user()->id)) {
 //            $authId = Auth::user()->id;
 //        } 

 //        $posts[$key]['authId'] = $authId;
	// }
	
    $bg = Setting::where('type', 'bg')->first();
    $font = Setting::where('type', 'font')->first();

    return view('preview', ['posts' => $posts, 'bg' => $bg, 'font' => $font]);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'alias', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles() {
        return $this->belongsToMany('App\Role', 'user_role', 'user_id', 'role_id');
    }

    public function hasAnyRole($roles) 
    {
        if(is_array($roles)) {
            foreach ($roles as $role) {
                if($this->hasRole($role)) {
                    return true;
                }
            }
        } else {
            if($this->hasRole($roles)) {
                return true;
            }
        }

        return false;
    }

    public function hasRole($role)
    {
        if($this->roles()->where('name', $role)->first()) {
            return true;
        }

        return false;
    } 
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Account Management</h1>
        </div>
    </div>

    <div class="panel-body">
        {!! Form::open([
        'action' => 'AdminUsersController@store',
        'method' => 'post',
        'class' => 'form-horizontal',
        'files' => true]) !!}
        
         <div class="form-group">
            {!! Form::label('employee_id', 'Registered ID No.', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::text('employee_id', null , ['class' => 'form-control', 'placeholder' => 'Registered ID No.']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('name', 'Fullname', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::text('name', null , ['class' => 'form-control', 'placeholder' => 'Fullname']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('name', 'Alias of A.K.A.', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::text('alias', null , ['class' => 'form-control', 'placeholder' => 'Alias of A.K.A.']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('email', 'Email', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::email('email', null , ['class' => 'form-control', 'placeholder' => 'Email']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title', 'Type', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                <select class="form-control" name="type">
                    <option value="staff">Staff</option>
                    <option value="faculty">Faculty</option>
                    <option value="student">Student</option>
                    <option value="admin">Admin</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('password', 'Password', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) !!}
            </div>

        </div>

        <div class="form-group">
            {!! Form::label('confirm', 'Confirm', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::password('confirm', ['class' => 'form-control', 'placeholder' => 'Confirm']) !!}
            </div>

        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9 pull-right">
                {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
            </div>
        </div>

        {{ csrf_field() }}
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Account Management</h1>
        </div>
    </div>

    <div class="panel-body">
        {!!
       Form::model($user, ['route' => ['users.update', $user->id],
      'method' => 'put',
      'class' => 'form-horizontal',
      'files' => true]) !!}
    
        <div class="form-group">
            {!! Form::label('employee_id', 'Registered ID No.', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::text('employee_id', $user->employee_id , ['class' => 'form-control', 'placeholder' => 'Registered ID No.']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('name', 'Fullname', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::text('name', $user->name , ['class' => 'form-control', 'placeholder' => 'Fullname']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('name', 'Alias of A.K.A', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::text('alias', $user->alias , ['class' => 'form-control', 'placeholder' => 'Alias of A.K.A']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('email', 'Email', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                {!! Form::email('email', $user->email , ['class' => 'form-control', 'placeholder' => 'Email']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title', 'Type', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-3">
                <select class="form-control" name="type">
                    <option value="staff" {{$user->type == 'staff' ? 'selected': ''}}>Staff</option>
                    <option value="faculty" {{$user->type == 'faculty' ? 'selected': ''}}>Faculty</option>
                    <option value="student" {{$user->type == 'student' ? 'selected': ''}}>Student</option>
                    <option value="admin" {{$user->type == 'admin' ? 'selected': ''}}>Admin</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9 pull-right">
                {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
            </div>
        </div>

        {{ csrf_field() }}
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Account Management</h1>

        <form class="pull-right input-group col-md-3">
            <input type="text" id="search"  class="form-control" name="q" placeholder="Search" value="{{isset ($_GET['q']) ? $_GET['q'] : ''}}">
        </form>
    </div>
</div>

<div class="panel-body">
    <a href="/admin/users/create" class="btn btn-success">Create</a>
    <table class="table table-hover ">
        <thead>
        <tr>
            <th>Registered ID N o.</th>
            <th>Fullname</th>
            <th>Alias of A.K.A</th>
            <th>Email</th>
            <th>Type</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($users as $user)
        <tr>
            <td>{{ $user->employee_id }}</td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->alias }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->type }}</td>
            <td>
                <a href="{{route('users.edit', $user->id) }}" class="btn btn-warning">Edit</a>
                {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id], 'style' => 'display:inline']) !!}
                {{ csrf_field() }}
                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>

<script type="text/javascript">
 
$('#search').on('keyup',function(){
 
value=$(this).val();
 console.log(value);
$.ajax({
 
type : 'get',
 
url : '/ajax/users',
 
data:{'q':value},
 
success:function(data){
 console.log(data);
$('tbody').html(data);
 
 }
 
});
 
 
 
})
 
</script>

@endsection