routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Post;
use App\Setting;
use App\Rating;
use App\View;
use App\User;

Auth::routes();

Route::get('/', function() {

	$filter['flag'] = 1; 

    $posts = Post::where($filter);
    if(isset(\Auth::user()->type) && \Auth::user()->type != 'admin') {
        $posts->where('bulletin', 'like', '%'.\Auth::user()->type.'%');
    }

	$posts = $posts->get();

	foreach ($posts as $key => $post) {
		if(isset($post->files[0]->filename)) {
			$posts[$key]['filename'] = $post->files[0]->filename;
		} else {
			$posts[$key]['filename'] = '';
		}

		$ratings = Rating::where('post_id', $post->id)->get();

		$aveRating = 0;

		if(!$ratings->isEmpty()) {
			$rate = [
				5 => 0,
				4 => 0,
				3 => 0,
				2 => 0,
				1 => 0
				];
			foreach ($ratings as $value) {
				$rate[$value['rating']]++; 
			}


			$totalWeight = 0;
			$totalReviews = 0;

			foreach ($rate as $weight => $numberofReviews) {
			    $WeightMultipliedByNumber = $weight * $numberofReviews;
			    $totalWeight += $WeightMultipliedByNumber;
			    $totalReviews += $numberofReviews;
			}

			//divide the total weight by total number of reviews
			$aveRating = $totalWeight / $totalReviews;

			$aveRating = floor($aveRating);
		}

		$posts[$key]['aveRating'] = $aveRating;

		 $authId = null;
        if(isset(Auth::user()->id)) {
            $authId = Auth::user()->id;
        } 

        $posts[$key]['authId'] = $authId;

        $limit = 250;

         $string = strip_tags($post['desc']);

        if (strlen($string) > $limit) {
            // truncate string
            $stringCut = substr($string, 0, $limit);

            // make sure it ends in a word so assassinate doesn't become ass...
            $string = substr($stringCut, 0, strrpos($stringCut, ' ')).'... <a href="/post/'.$post['id'].'">Read More</a>';
        }

        $posts[$key]['desc'] = $string;

	}

    $bg = Setting::where('type', 'bg')->first();
    $font = Setting::where('type', 'font')->first();


    return view('index', ['posts' => $posts, 'bg' => $bg, 'font' => $font]);
});

Route::get('/home', 'PostsController@index');
Route::get('/post/{id}', function($id) {
	$post = Post::where('id', $id)->first();

	$view = new View();
	$view->post_id = $id;

	$view->save();

	$ratings = Rating::where('post_id', $id)->get();

	$aveRating = 0;

	if(!$ratings->isEmpty()) {
		$rate = [
			5 => 0,
			4 => 0,
			3 => 0,
			2 => 0,
			1 => 0
			];
		foreach ($ratings as $key => $value) {
			$rate[$value['rating']]++; 
		}


		$totalWeight = 0;
		$totalReviews = 0;

		foreach ($rate as $weight => $numberofReviews) {
		    $WeightMultipliedByNumber = $weight * $numberofReviews;
		    $totalWeight += $WeightMultipliedByNumber;
		    $totalReviews += $numberofReviews;
		}

		//divide the total weight by total number of reviews
		$aveRating = $totalWeight / $totalReviews;

		$aveRating = floor($aveRating);
	}

    $template = Setting::where('type', 'template')->first();

  $bg = Setting::where('type', 'bg')->first();
    $font = Setting::where('type', 'font')->first();


    return view('post-detail', ['post' => $post, 'aveRating' => $aveRating, 'template' => $template, 'bg' => $bg, 'font' => $font]);
});

Route::get('/admin', 'AdminController@index');
Route::resource('/admin/users','AdminUsersController');
Route::resource('/admin/posts', 'PostsController');
Route::get('/admin/view', 'PostsController@view');
Route::get('/admin/rating', 'PostsController@rating');
Route::get('/admin/bulletin', 'PostsController@bulletin');

Route::get('/admin/users', [
	'uses' => 'AdminUsersController@index',
	'as' => 'admin',
	'middleware' => 'roles',
	'roles' => ['admin']
]);	

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/api/posts', 'ApiPostsController@index');
Route::post('/api/rating/create', 'ApiPostsController@rating');
Route::get('/api/views', 'ApiPostsController@views');
Route::get('/admin/settings', 'SettingController@index');
Route::get('/admin/settings/bg', 'SettingController@bg');
Route::resource('/admin/settings', 'SettingController');
Route::get('/api/settings', 'ApiPostsController@template');
Route::get('user/{id}/delete', ['as' => 'users.delete', 'uses' => 'AdminUsersController@destroy']);

Route::get('/api/posts/preview', 'ApiPostsController@preview');

Route::get('/ajax/users', 'AdminUsersController@indexApi');
Route::get('/preview', function() {

	if(isset($_GET['type'])) {

		if($_GET['type'] == 'general') {
            $posts = Post::orderBy('id', 'DESC')->get();

		}  else {
            $posts = Post::where('bulletin', 'like', '%'.$_GET['type'].'%')
            ->orderBy('id', 'DESC')->get();
			
		}
   } else if(isset($_GET['q']) && !empty($_GET['q'])) { 
        $posts = new Post();

        $posts = $posts->where('author', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('title', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('type', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('bulletin', 'LIKE', "%" . $_GET['q'] . "%")
                ->orWhere('desc', 'LIKE', "%" . $_GET['q'] . "%")->get();
    }


	// foreach ($posts as $key => $post) {
	// 	if(isset($post->files[0]->filename)) {
	// 		$posts[$key]['filename'] = $post->files[0]->filename;
	// 	} else {
	// 		$posts[$key]['filename'] = '';
	// 	}

	// 	$ratings = Rating::where('post_id', $post->id)->get();

	// 	$aveRating = 0;

	// 	if(!$ratings->isEmpty()) {
	// 		$rate = [
	// 			5 => 0,
	// 			4 => 0,
	// 			3 => 0,
	// 			2 => 0,
	// 			1 => 0
	// 			];
	// 		foreach ($ratings as $key => $value) {
	// 			$rate[$value['rating']]++; 
	// 		}


	// 		$totalWeight = 0;
	// 		$totalReviews = 0;

	// 		foreach ($rate as $weight => $numberofReviews) {
	// 		    $WeightMultipliedByNumber = $weight * $numberofReviews;
	// 		    $totalWeight += $WeightMultipliedByNumber;
	// 		    $totalReviews += $numberofReviews;
	// 		}

	// 		//divide the total weight by total number of reviews
	// 		$aveRating = $totalWeight / $totalReviews;
	// 	}

	// 	$posts[$key]['aveRating'] = $aveRating;

	// 	 $authId = null;
 //        if(isset(Auth::user()->id)) {
 //            $authId = Auth::user()->id;
 //        } 

 //        $posts[$key]['authId'] = $authId;
	// }
	
    $bg = Setting::where('type', 'bg')->first();
    $font = Setting::where('type', 'font')->first();

    return view('preview', ['posts' => $posts, 'bg' => $bg, 'font' => $font]);
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'name',
        'guide',
        'content',
        'budget',
        'distance',
        'eta',
        'rank',
        'likes',
        'views',
    ];

    public function files() {
        return $this->hasMany('App\File');
    }

    public function views() {
        return $this->hasMany('App\View');
    }

}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Rating;
use App\Post;
use App\File;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(isset($_GET['type'])) {
            $posts = Post::where('bulletin', 'like', '%'.$_GET['type'].'%')->get();
        } else if(isset($_GET['q']) && !empty($_GET['q'])) { 
            $posts = new Post();

            $posts = $posts->where('author', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('title', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('type', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('bulletin', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('desc', 'LIKE', "%" . $_GET['q'] . "%")->get();
        } else {
            $posts = Post::orderBy('id', 'DESC')->get();
        }

        return view('admin.posts.index', compact('posts'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function view()
    {   


        if(isset($_GET['q']) && !empty($_GET['q'])) { 
            $posts = new Post();
            $posts = $posts->where('author', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('title', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('type', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('bulletin', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('desc', 'LIKE', "%" . $_GET['q'] . "%")->get();
        } else {
            $posts = Post::all();
        }

        foreach ($posts as $key => $value) {
            $posts[$key]['view'] = \DB::table('views')
            ->where('post_id', $value['id'])
            ->get()->count();
        }

        $charts = \DB::select('select count(*) as total, year(created_at) as year from views group by year(created_at)');



        foreach ($charts as $key => $chart) {
            $data[$chart->year]['year'] = $chart->year;
            $data[$chart->year]['total'] = $chart->total;
        }


        for ($i = min($data)['year']; $i <= 2022; $i++) {
            if(!isset($data[$i])) {
                $data[$i]['total'] = 0;
                $data[$i]['year'] = $i;
            }
        }
        
        // dd($data);
        return view('admin.posts.view', [
            'posts' => $posts, 
            'charts' => $data, 
            'startYear' => min($data)
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function rating()
    {   

        $filter['flag'] = 1; 

        $posts = Post::where($filter);
        // if(isset(\Auth::user()->type) && \Auth::user()->type != 'admin') {
        //     $posts->where('bulletin', 'like', '%'.\Auth::user()->type.'%');
        // }

        $posts = $posts->get();

        foreach ($posts as $key => $post) {
            if(isset($post->files[0]->filename)) {
                $posts[$key]['filename'] = $post->files[0]->filename;
            } else {
                $posts[$key]['filename'] = '';
            }

            $ratings = Rating::where('post_id', $post->id)->get();

            $aveRating = 0;

            if(!$ratings->isEmpty()) {
                $rate = [
                    5 => 0,
                    4 => 0,
                    3 => 0,
                    2 => 0,
                    1 => 0
                    ];
                foreach ($ratings as $value) {
                    $rate[$value['rating']]++; 
                }


                $totalWeight = 0;
                $totalReviews = 0;

                foreach ($rate as $weight => $numberofReviews) {
                    $WeightMultipliedByNumber = $weight * $numberofReviews;
                    $totalWeight += $WeightMultipliedByNumber;
                    $totalReviews += $numberofReviews;
                }

                //divide the total weight by total number of reviews
                $aveRating = $totalWeight / $totalReviews;

                $aveRating = floor($aveRating);
                // dd($aveRating);
            }

            $posts[$key]['aveRating'] = $aveRating;

             $authId = null;
            // if(isset(Auth::user()->id)) {
            //     $authId = Auth::user()->id;
            // } 

            $posts[$key]['authId'] = $authId;

            $limit = 250;

             $string = strip_tags($post['desc']);

            if (strlen($string) > $limit) {
                // truncate string
                $stringCut = substr($string, 0, $limit);

                // make sure it ends in a word so assassinate doesn't become ass...
                $string = substr($stringCut, 0, strrpos($stringCut, ' ')).'... <a href="/post/'.$post['id'].'">Read More</a>';
            }

            $posts[$key]['desc'] = $string;

        }

        $rating = [];
        foreach ($posts as $key => $value) {

            if ($value['aveRating'] == 1) {
                $rating[1] = isset($rating[1]) ? $rating[1] + 1 : 1;
            }

            if ($value['aveRating'] == 2) {
                $rating[2] = isset($rating[2]) ? $rating[2] + 1 : 1;
            }

            if ($value['aveRating'] == 3) {
                $rating[3] = isset($rating[3]) ? $rating[3] + 1 : 1;
            }

            if ($value['aveRating'] == 4) {
                $rating[4] = isset($rating[4]) ? $rating[4] + 1 : 1;
            }

            if ($value['aveRating'] == 5) {
                $rating[5] = isset($rating[5]) ? $rating[5] + 1 : 1;
            }
        }

        if (!isset($rating[1])) {
            $rating[1] = 0;
        }

        if (!isset($rating[2])) {
            $rating[2] = 0;
        }

        if (!isset($rating[3])) {
            $rating[3] = 0;
        }

        if (!isset($rating[4])) {
            $rating[4] = 0;
        }

        if (!isset($rating[5])) {
            $rating[5] = 0;
        }

        // if(isset($_GET['q']) && !empty($_GET['q'])) { 
        //     $posts = new Post();
        //     $posts = $posts->where('author', 'LIKE', "%" . $_GET['q'] . "%")
        //             ->orWhere('title', 'LIKE', "%" . $_GET['q'] . "%")
        //             ->orWhere('type', 'LIKE', "%" . $_GET['q'] . "%")
        //             ->orWhere('bulletin', 'LIKE', "%" . $_GET['q'] . "%")
        //             ->orWhere('desc', 'LIKE', "%" . $_GET['q'] . "%")->get();
        // } else {
        //     $posts = Post::all();
        // }

        // foreach ($posts as $key => $value) {
        //     $posts[$key]['view'] = \DB::table('views')
        //     ->where('post_id', $value['id'])
        //     ->get()->count();
        // }

        // $charts = \DB::select('select count(*) as total, year(created_at) as year from views group by year(created_at)');



        // foreach ($charts as $key => $chart) {
        //     $data[$chart->year]['year'] = $chart->year;
        //     $data[$chart->year]['total'] = $chart->total;
        // }


        // for ($i = min($data)['year']; $i <= 2022; $i++) {
        //     if(!isset($data[$i])) {
        //         $data[$i]['total'] = 0;
        //         $data[$i]['year'] = $i;
        //     }
        // }
        
        return view('admin.posts.rating', [
            'posts' => $posts, 
            'rating' => $rating, 
            // 'startYear' => min($data)
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function bulletin()
    {   
        if(isset($_GET['type'])) {
            $posts = Post::where('bulletin', 'like', '%'.$_GET['type'].'%')
            ->orderBy('id', 'DESC')->get();
        } else if(isset($_GET['q']) && !empty($_GET['q'])) { 
            $posts = new Post();

            $posts = $posts->where('author', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('title', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('type', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('bulletin', 'LIKE', "%" . $_GET['q'] . "%")
                    ->orWhere('desc', 'LIKE', "%" . $_GET['q'] . "%")->get();
        } else {
            $posts = Post::orderBy('id', 'DESC')->get();
        }

        return view('admin.posts.bulletin', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = [
            'name' => 'news', 
            'name' => 'post'
        ];
        return view('admin.posts.create', compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $post = new Post();
        $post->author = $input['author'];
        $post->title = $input['title'];
        $post->desc = $input['desc'];
        $post->bulletin = json_encode($input['bulletin']);
        $post->type = $input['type'];
        $post->video = !empty($input['video']) ? $this->getYoutubeEmbedUrl($input['video']) : '';

        $post->save();

        $files = $request->file('files');

        if($request->hasFile('files'))
        {
            foreach ($files as $file) {
                $name = $file->getClientOriginalName();
                $file->move('images',  $name);

                $post->files()->save(new File(['filename' => $name]));
            }
        }

        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *

resources/views/admin/posts/bulletin.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Bulletin's Preview Management | {{ isset ($_GET['type']) ? ucwords($_GET['type']) : 'General'}}</h1>
    </div>
</div>

<div class="panel-body">

    <iframe src="/preview?type=<?php echo isset($_GET['type']) ? $_GET['type']: 'all'?>" frameborder="0" width="100%" height="1500"></iframe>
</div>
@endsection

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Posts</h1>
        </div>
    </div>

    <div class="panel-body">
        {!! Form::open([
        'action' => 'PostsController@store',
        'method' => 'post',
        'class' => 'form-horizontal',
        'files' => true]) !!}
    
        <div class="form-group">
            {!! Form::label('author', 'Author', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-6">
                {!! Form::text('author', null , ['class' => 'form-control', 'placeholder' => 'Author']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title', 'Title', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-6">
                {!! Form::text('title', null , ['class' => 'form-control', 'placeholder' => 'Title']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title', 'Description', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-6">
                {!! Form::textarea('desc', null , ['class' => 'form-control', 'placeholder' => 'Description', 'required' => 'required', 'id' => 'summernote']) !!}
            </div>
        </div>
        
        <div class="form-group">
            {!! Form::label('title', 'Type', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-6">
                <select class="form-control" name="type">
                    <option value="News">News</option>
                    <option value="Announcement">Announcement</option>
                    <option value="Post">Post</option>
                </select>
            </div>
        </div>

       <div class="form-group{ clearfix">
            <label class="control-label col-sm-3">Bulletin</label>
            <div class="col-sm-6">
                <div data-do="tag-field" class="tag-field">
                        <div class="tag">
                            <input type="text" class="tag-input text-field" name="bulletin[]" placeholder="Add Tag" value="" />
                            <a class="remove" href="javascript:void(0)"><i class="fa fa-times"></i></a>
                        </div>
                </div>

                <div class="input-suggestion hide">
                    <ul class="suggestion-list"></ul>
                </div>

                <em><strong>Note: </strong>staff, faculty, student.</em>
               
            </div>
            <script id="tag-translations" type="text/json">Tag:Tag</script>
        </div>

        <div class="form-group">
            {!! Form::label('video', 'Video', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-6">
                {!! Form::text('video', null , ['class' => 'form-control', 'placeholder' => 'https://www.youtube.com/watch?v=DP-ksbqk5ds']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title', 'Image', ['class' => 'col-sm-3 control-label']) !!}
            <div class="col-sm-6">
                {!! Form::file('files[]', null , ['class' => 'form-control', 'placeholder' => 'Content']) !!}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9 pull-right">
                {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
            </div>
        </div>

        {{ csrf_field() }}
        {!! Form::close() !!}
    </div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#summernote').summernote({
          height:300,
        });
    });
</script>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{{ isset ($_GET['type']) ? ucwords($_GET['type']) : ''}} Post Management</h1>

         <form class="pull-right input-group col-md-3">
            <input type="text" id="search" class="form-control" name="q" placeholder="Search" value="{{isset ($_GET['q']) ? $_GET['q'] : ''}}">
            <span class="input-group-btn">
                <input class="btn btn-info" type="submit" value="Submit">
            </span>
        </form>
    </div>
</div>

<div class="panel-body">
    <a href="/admin/posts/create" class="btn btn-success">Create</a>

    <table class="table table-hover " style="table-layout: fixed;">
        <thead>
        <tr>
            <th>Post ID</th>
            <th>Title</th>
            <th>Author</th>
            <th class="col-sm-2">Description</th>
            <th>Type</th>
            <th>Bulletin</th>
            <th>Published</th>
            <th class="col-sm-3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($posts as $post)
        <tr>
            <td class="col-sm-2">{{ $post->id }}</td>
            <td class="col-sm-2">{{ $post->title }}</td>
            <td class="col-sm-2"><i>{{ $post->alias }}</i>{{ $post->author }}</td>
            <td class="col-sm-4">@if (!$post->files->isEmpty())
        <a href="#" id="pop">
    <img id="imageresource" src="/images/{{ $post->files{0}->filename }}"   width="100">
                @endif
     
</a>
{!! \Illuminate\Support\Str::words($post->desc, 20,'....')  !!}
                </td>
            <td>{{ $post->type }}</td>
            <td>{{ ucfirst(trans($post->bulletin)) }}</td>
            <td>{{ $post->flag == 1 ? 'Yes' : 'No' }}</td>
            <td >
                @if (Auth::user()->type == 'admin') 
                    {!! Form::open(['method' => 'PUT','route' => ['posts.update', $post->id], 'style' => 'display:inline']) !!}
                        {{ csrf_field() }}

                        @if ($post->flag == 1)
                        {!! Form::hidden('flag', 0) !!}
                        {!! Form::submit('Unpublish', ['class' => 'btn btn-info']) !!}
                        @else
                        {!! Form::hidden('flag', 1) !!}
                        {!! Form::submit('Publish', ['class' => 'btn btn-info']) !!}
                        @endif
                    {!! Form::close() !!}
                @endif
                <a href="{{route('posts.edit', $post->id) }}" class="btn btn-warning">Edit</a>
                {!! Form::open(['method' => 'DELETE','route' => ['posts.destroy', $post->id], 'style' => 'display:inline']) !!}
                {{ csrf_field() }}
                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                {!! Form::close() !!}
            </td>
        </tr>

        
   
        @endforeach
        </tbody>
    </table>
</div>

<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      </div>
      <div class="modal-body">
        <img src="" id="imagepreview" style="width: 100%; " >
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
 
$('#search').on('keyup',function(){
 
value=$(this).val();
 console.log(value);
$.ajax({
 
type : 'get',
 
url : '/ajax/users',
 
data:{'q':value},
 
success:function(data){
$('tbody').html(data);
 
 }
 
});
 
 
 
})
 
</script>

<script>
    $("#pop").on("click", function() {
   $('#imagepreview').attr('src', $('#imageresource').attr('src')); // here asign the image to the modal when the user click the enlarge link
   $('#imagemodal').modal('show'); // imagemodal is the id attribute assigned to the bootstrap modal, then i use the show function
});
</script>
@endsection

resources/views/admin/posts/view.blade.php
@extends('layouts.admin')

@section('content')


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Report Management | Total No. of Views</h1>

         <form class="pull-right input-group col-md-3">
            <input type="text" class="form-control" name="q" placeholder="Search" value="{{isset ($_GET['q']) ? $_GET['q'] : ''}}">
            <span class="input-group-btn" style="font-size: 10px !important;">
                <input class="btn btn-info" type="submit" value="Submit"> &nbsp;

                <a href="javascript:void(0);" onClick="window.print()" class="btn btn-success">Print</a>
            </span>
        </form>
    </div>
</div>
 <script type="text/javascript" src="/highcharts/highcharts.js"></script>
    @if ($posts->count() > 0)

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<div class="panel-body">
    <table class="table table-hover ">
        <thead>
        <tr>
            <th>View</th>
            <th>Image</th>
            <th>Title</th>
            <th>Author</th>
            <th>Type</th>
            <th>Bulletin</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($posts as $post)
        <tr>
            <td><h2>{{ $post->view}}</h2></td>
            <td>
                @if (!$post->files->isEmpty())
                <img width="100" src="/images/{{ $post->files{0}->filename }}" alt=""></td>
                @endif

            <td class="col-sm-2">{{ $post->title }}</td>
            <td class="col-sm-2">{{ $post->author }}</td>
            <td>{{ $post->type }}</td>
            <td>{{ ucfirst(trans($post->bulletin)) }}</td>
            
        </tr>
        @endforeach
        </tbody>
    </table>
</div>
@else
<h3><i>No result.</i></h3>
    @endif


<script>
 Highcharts.chart('container', {

    title: {
        text: 'Number of Times the Post Have Views Graph'
    },

    subtitle: {
        text: ''
    },

    yAxis: {
        title: {
            text: 'Number of Viewer(s)'
        }
    },
    legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'middle'
    },

    plotOptions: {
        series: {
            label: {
                connectorAllowed: false
            },
            pointStart: {{$startYear['year']}},
        }
    },

    series: [{
        name: 'Posts',
        data: [
        @foreach ($charts as $chart)
            {{$chart['total']}},
        @endforeach

        ]
    }],

    responsive: {
        rules: [{
            condition: {
                maxWidth: 00
            },
            chartOptions: {
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom'
                }
            }
        }]
    }

});
</script>
@endsection